### ISSUE TITLE
Because of inventory_sales module (MSI) : Backorder Item Status is not showing if we placed order with backorder item in magento2.3.x 

### ISSUE THREAD

**Issue by pushpagupta-magento** [magento/inventory#2218]
### Preconditions (*)

1. Magento version 2.3.0
2. Should have inventory_sales module (MSI)

### Steps to reproduce (*)

1. Set a product up as backorderable - 0 quantity stock, "allow orders below 0", in stock, enabled
2. As a frontend customer, add this backordered product to a cart
3. Add an additional "normal" stock item to the cart (not backordered - this step may not be strictly required but is useful to make it easier to compare normal vs backordered line items)
4. Go through a normal customer frontend order process with this product
5. After placing the order, note that in the order history / admin order view that the order items list shows **ordered** in the "item status" column for **backorder** item and a **normal** item as well - **this is incorrect**

![actual](https://user-images.githubusercontent.com/50232568/57134156-da982d80-6dc2-11e9-8e09-ec258c9067f0.jpg)

You can also look in the database and see that the **sales_order_item** table has a **qty_backordered** column with **NULL** - again, this is unexpected and incorrect

<img width="501" alt="actual-db" src="https://user-images.githubusercontent.com/50232568/57134165-e7b51c80-6dc2-11e9-904b-5df24950b717.png">

### Expected result (*)

1. After placing the order, note that in the order history / admin order view that the order items list shows **ordered** in the "item status" column for a **normal** item and **backordered** in the "item status" column for a **backorder** item - **this is correct**

<img width="816" alt="expected" src="https://user-images.githubusercontent.com/50232568/57134197-00253700-6dc3-11e9-9fe1-dd7f77af4339.png">

You can also look in the database and see that the ** table has a **qty_backordered** column with 1 - again, this is expected and correct

<img width="824" alt="excepted-db" src="https://user-images.githubusercontent.com/50232568/57134213-07e4db80-6dc3-11e9-935c-7c6fa1851295.png">

### Actual result (*)

1. After placing the order, note that in the order history / admin order view that the order items list shows **ordered** in the "item status" column for **backorder** item and a **normal** item as well - **this is incorrect**

**Comment by pushpagupta-magento** [comment]
Hi, please assign this issue to me. I am not able to assign this to me.

**Comment by pushpagupta-magento** [comment]
@magento-engcom-team give me 2.3-develop instance

**Comment by pushpagupta-magento** [comment]
Hi Team : I have found the solution for it and working on it and soon will generate the PR.

**Comment by pushpagupta-magento** [comment]
I am working on this at #dmcdindia19

**Comment by maghamed** [comment]
hey @pushpagupta-magento  I granted you write permissions for MSI repo, so that since now you can create branches in MSI repo but not to fork MSI in own fork. Also, you can self-assign yourself to any tickets from the MSI backlog

**Comment by gwharton** [comment]
See https://github.com/magento/inventory/pull/2452 as an alternative solution.

**Comment by gwharton** [comment]
Fixed in 2.4

**Comment by mattwellss** [comment]
@gwharton sorry to bother, but I'm still experiencing this (`null` values for `qty_backordered`) on 2.4.3-p1 (which installs the newest tag of the inventory module metapackage). Do you know which commit(s) resolve the issue?

**Comment by gwharton** [comment]
This remains broken in all current Magento releases i am afraid. I created several PRs to fix it, but all got ignored so they all got closed by stale bot.

I realised that the backorder qty that is stored in the dB is obtained from the default stock/source. I switched my store to only use a single source, the default one so it works for me but if you use other sources, then it will fail and will record whatever backorder qty would be relevant for default source.

I got tired of getting core team to recognise the issue as the fix requires changes to both core and MSI at the same time.

Perhaps raise a new issue and I'll add my thoughts to it and see if we can get traction again

**Comment by mattwellss** [comment]
Thank you for the quick response! I've been reviewing your PR, and comparing it to my own WIP changes it seems like we're on similar tracks.

Really appreciate the work you put in.

**Comment by gwharton** [comment]
Yeah, MSI needs to return the backorder qty, which it curreny doesn't. And then core needs to not override the qty returned by MSI, with the backorder qty from default stock, which it currently does.
