### ISSUE TITLE
Inventory doesn't "follow" when SKU changes, making products disappear

### ISSUE THREAD

**Issue by iphigenie** [magento/inventory#3118]
### Preconditions (*)

Tested on my instance of 2.3.4 with inventory release 1.1.4 from january
Site with MSI enabled
Products

### Steps to reproduce (*)

Add stock to the products, save, index, check that all is right with these products

Change the product sku, save

reindex etc.

### Expected result (*)

Stock entries should be updated for the new sku
Product should remain in stock and working on the site

### Actual result (*)

On the front end the product will vanish from categories and search

Stock entries remain for the old sku

New stock entries are not created with the new sku?

This gets eventually fixes itself for the simple products if you go in and manually re-set the stocks . It does not fix itself for bundles, I could not find a way for a sku changed bundle to put itself back in those tables, not by making it stock managed and back, not with batch update... Had to change table content

This scenario happens if you "save and copy" a product in the interface since the product is created with an automatic sku and a copy of the stock levels, then you change the sku. Bam, new product is not showing. I guess it is something to add to the "if you copy a product, you need to redo the images AND the stocks, they look OK but they are not"

### Additional:

`SELECT * FROM inventory_source_item WHERE sku not in (select sku from catalog_product_entity)` returns a lot of hits on my site, which indicates this probably doesn't deal with deletions either. 

Should the composite products be in there at all or not? I am not sure. In the test data they arent, but in the test data if you turn MSI on the bundle vanishes from the frontend

Question: should the tables and indexers be able to cope with SKU changes and it is just a bug on my site or is it something not implemented. I didn't see it in the observers on products, but I didnt look in every inventory submodule

Note: most of these products were created and sometimes modified through the data migration module - it is possible this is a quirk from this.

**Comment by iphigenie** [comment]
Clearly if you are going to use a changeable - in your own setup sku can change, id cannot - value like SKU as a key in your tables, then you need to have either foreign keys and cascade changes OR you need an Observer on product save for sku change as well as for stock change.

**Comment by smoskaluk** [comment]
Hi @iphigenie ! This issue fixed by https://github.com/magento/inventory/pull/2795, please have a look.

**Comment by dbashyal** [comment]
Still the same issue in Magento 2.4.3-P3. I changed the product SKU recently. Noticed the order with the old SKU failed to create a shipment. I updated records in sales_order_item and tried to ship again but still looking for the old SKU. Then found old SKUs still in the table inventory_source_item. I did reindex EAV & inventory but still, those old SKUs are there and can't create a shipment.

To fix the shipment issue, I had to update the `simple_sku` within the `product_options` column.
