### ISSUE TITLE
Configurable products marked out of stock incorrectly

### ISSUE THREAD

**Issue by aligent-lturner** [magento/inventory#3350]
### Preconditions (*)

1. Non-default inventory source and stock has been set up
2. Configurable product set up with one or more simple products
3. Simple products are all out of stock at `default` source
4. At least one simple product in stock (with plenty of stock) at other sources

### Steps to reproduce (*)

1. Create and ship an order with a configurable product using a source other than the default source.
2. Wait for stock reindexing and check the salable status of the configurable product

### Expected result (*)

1. Configurable product remains salable, as simple products are still salable at non-default sources

### Actual result (*)

1. Configurable product is marked as not salable

### Additional information
I believe this is caused by https://github.com/magento/inventory/blob/e08a47c3501de2cbff42b3ac05058ce15d620e75/InventoryConfigurableProduct/Plugin/InventoryApi/UpdateParentStockStatusInLegacyStockPlugin.php

This plugin updates the status of configurable products based on the stock status of their simple components, but it does not take the inventory setup into account at all. In our case, the default source has not been updated at all, yet the result is that the `cataloginventory_stock_item` table is updated for the configurable product. As a result of this, the inventory stock indexer takes this changed value into account and subsequently marks the configurable as not salable for any non-default stocks.

There is an additional plugin https://github.com/magento/inventory/blob/e08a47c3501de2cbff42b3ac05058ce15d620e75/InventoryConfigurableProduct/Plugin/InventoryApi/UpdateConfigurableProductParentStockStatus.php that was added later that appears to be for much the same purpose, but with additional checks that single source mode and a single store are being used.

**Comment by IvanVizcaino** [comment]
I have the same problem. Any temporal solution available? Thanks

**Comment by maheshm-kensium** [comment]
HI @aligent-lturner ,

We are also facing similar issue, when we installed either 2.4.4 CE/EE the MSI modules will be installed as part Magento Core application through composer and enabled by default.

When MSI modules are enabled the configurable parent product stock status are not updating correctly and always stays in Out Of Stock (OOS) once the stock status changed from Is In stock to OOS (either by updating child product stock status or parent).

If we disable MSI Inventory modules then configurable parent product stock status updating as expected.

I already reported this below, so please refer for information.
https://github.com/magento/magento2/issues/35494#issuecomment-1143465470
https://github.com/magento/magento2/issues/35494#issuecomment-1138697607

Expecting, someone going to address this ASAP as it is Major bug for all vendors. Please let me know if anyone needs additional information.

**Comment by IvanVizcaino** [comment]
Hello, I have a temporal solution that is working for me. We are override \Magento\ConfigurableProduct\Model\Inventory\ChangeParentStockStatus The problem is the variable $childrenIsInStock is initialized a false and then never change the value. We are calculated the value of this variable with the sum of sources quantities. This is incorrect if you use stock for websites, but this is a fastest solution for us to resolve the problem in production environment. This is my function processStockForParent
```

private function processStockForParent(int $productId): void
    {
        $criteria = $this->criteriaInterfaceFactory->create();
        $criteria->setScopeFilter($this->stockConfiguration->getDefaultScopeId());

        $criteria->setProductsFilter($productId);
        $stockItemCollection = $this->stockItemRepository->getList($criteria);
        $allItems = $stockItemCollection->getItems();
        if (empty($allItems)) {
            return;
        }
        $parentStockItem = array_shift($allItems);

        $childrenIds = $this->configurableType->getChildrenIds($productId);
        $criteria->setProductsFilter($childrenIds);
        $stockItemCollection = $this->stockItemRepository->getList($criteria);
        $allItems = $stockItemCollection->getItems();

        $childrenIsInStock = false;
        $childs = array();
        if(isset($childrenIds[0])){
            $childs = $this->productCollection->addAttributeToSelect('sku')
                ->addFieldToFilter('entity_id', array('in' => $childrenIds[0]));
        }
       
        foreach ($childs as $childItem) {
            $salableQty = $this->getSalableQuantityDataBySku->execute($childItem->getSku());
            $qty = 0;
            foreach($salableQty as $source){
                $qty += $source['qty'];
            }

            if ($qty > 0) {
                $childrenIsInStock = true;
                break;
            }
        }


        if ($this->isNeedToUpdateParent($parentStockItem, $childrenIsInStock)) {
            $parentStockItem->setIsInStock($childrenIsInStock);
            $parentStockItem->setStockStatusChangedAuto(1);
            $this->stockItemRepository->save($parentStockItem);
        }
    }


```

**Comment by alvinnguyen** [comment]
Is this related to https://support.magento.com/hc/en-us/articles/4428085214093-MDVA-42584-Stock-status-of-configurable-product-not-updated-automatically? It might not be as the patch mentioned the issues is via simple product being updated via API or import.

**Comment by maheshm-kensium** [comment]
Hi, has anyone looking in to this issue?

**Comment by danielrussob** [comment]
solved in quality patch: MDVA-41061-V4 and ACSD-45488

https://devdocs.magento.com/quality-patches/tool.html#patch-grid

**Comment by Playhf** [comment]
> ACSD-45488

Seems like it wasn't solved. Still experiencing an issue with it. Configurable goes OOS

**Comment by indunie** [comment]
Experienced the same. Below patches didn't solve the issue. Any recent update?
MDVA-41061-V4 and ACSD-45488

**Comment by sohelrana09** [comment]
After shipment, the configurable product goes OOS just because of https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/ConfigurableProduct/Model/Inventory/ChangeParentStockStatus.php#L100. 2.4.4 introduced with https://github.com/magento/inventory/blob/e08a47c3501de2cbff42b3ac05058ce15d620e75/InventoryConfigurableProduct/Plugin/InventoryApi/UpdateParentStockStatusInLegacyStockPlugin.php. When you have more than one source, **cataloginventory_stock_item** table stock status never update and your entire things will broken. Made adjustment with MSI like @IvanVizcaino did.

**Comment by cuongho803** [comment]
Hello there, I am facing this issue too, now I think the problem stays in this file "
"vendor/magento/module-inventory-configurable-product-indexer/Indexer/SelectBuilder.php".
`$select = $connection->select()
            ->from(
                ['stock' => $indexTableName],
                [
                    IndexStructure::SKU => 'parent_product_entity.sku',
                    IndexStructure::QUANTITY => 'SUM(stock.quantity)',
                    IndexStructure::IS_SALABLE => 'IF(inventory_stock_item.is_in_stock = 0, 0, MAX(stock.is_salable))',
                ]
            )->joinInner(
                ['product_entity' => $this->resourceConnection->getTableName('catalog_product_entity')],
                'product_entity.sku = stock.sku',
                []
            )->joinInner(
                ['parent_link' => $this->resourceConnection->getTableName('catalog_product_super_link')],
                'parent_link.product_id = product_entity.entity_id',
                []
            )->joinInner(
                ['parent_product_entity' => $this->resourceConnection->getTableName('catalog_product_entity')],
                'parent_product_entity.' . $linkField . ' = parent_link.parent_id',
                []
            )->joinLeft(
                ['inventory_stock_item' => $this->resourceConnection->getTableName('cataloginventory_stock_item')],
                'inventory_stock_item.product_id = parent_product_entity.entity_id'
                . ' AND inventory_stock_item.stock_id = ' . $this->defaultStockProvider->getId(),
                []
            )
            ->group(['parent_product_entity.sku']);

        return $select;`

The  IndexStructure::IS_SALABLE => 'IF(inventory_stock_item.is_in_stock = 0, 0, MAX(stock.is_salable))' condition seem wrong if the stock leagagy for configurable =0 therefore the is_salable for "inventory_stock_x" table wrong too. Can we change to  "IndexStructure::IS_SALABLE => 'IF(MAX(stock.is_salable),MAX(stock.is_salable),inventory_stock_item.is_in_stock)'," instead ?

**Comment by kwilliams-concentrix** [comment]
Any update here? We are experiencing in 2.4.5p-1 still

**Comment by RonanCapitaine** [comment]
Hello,

I got the same issue on my side. I temporary created this patch :
[AC_FIX_INVENTORY_CONFIGURABLE_STOCK_2.4.5.patch.txt](https://github.com/magento/inventory/files/10167273/AC_FIX_INVENTORY_CONFIGURABLE_STOCK_2.4.5.patch.txt)

**Comment by kamilszewczyk** [comment]
> Hello,
> 
> I got the same issue on my side. I temporary created this patch : [AC_FIX_INVENTORY_CONFIGURABLE_STOCK_2.4.5.patch.txt](https://github.com/magento/inventory/files/10167273/AC_FIX_INVENTORY_CONFIGURABLE_STOCK_2.4.5.patch.txt)

That patch seems to be working perfectly on 2.4.4 as well. Thanks!

**Comment by Stuart-1** [comment]
This issue also exists for bundled products

**Comment by barryvdh** [comment]
And grouped products..

**Comment by dverkade** [comment]
@RonanCapitaine are you able to raise a PR with your changes so that Magento / Adobe can review this and merge it in for the next release? That would help us all! Really appreciate your efforts.

**Comment by indrisepos** [comment]
> I got the same issue on my side. I temporary created this patch : [AC_FIX_INVENTORY_CONFIGURABLE_STOCK_2.4.5.patch.txt](https://github.com/magento/inventory/files/10167273/AC_FIX_INVENTORY_CONFIGURABLE_STOCK_2.4.5.patch.txt)

It works fine with Magento 2.4.5-p2! Thank you very much! I note that ACSD-45488 unfortunately did not fix it.

**Comment by vbuiendertech** [comment]
> Hello,
> 
> I got the same issue on my side. I temporary created this patch : [AC_FIX_INVENTORY_CONFIGURABLE_STOCK_2.4.5.patch.txt](https://github.com/magento/inventory/files/10167273/AC_FIX_INVENTORY_CONFIGURABLE_STOCK_2.4.5.patch.txt)

Hi Ronan,

I have the same issue on the Magento 2.4.6-p5.

But this patch can't apply on the M2.4.6-p5 because this file doesn't exist on this Magento version.

Please let me know if you have any solution for the last Magento version.

Thanks

**Comment by portchris** [comment]
For those still experiencing issues where configurable products stock status fails to update when child products come back in-stock.
I've created a patch which works for my Magento 2.4.6-p1 instance suffering from this virus...

```patch
--- a/vendor/magento/module-configurable-product/Model/Inventory/ChangeParentStockStatus.php	2024-06-27 11:54:34.515474442 +0100
+++ b/vendor/magento/module-configurable-product/Model/Inventory/ChangeParentStockStatus.php	2024-06-27 11:56:33.263253341 +0100
@@ -1,8 +1,10 @@
 <?php
+
 /**
  * Copyright © Magento, Inc. All rights reserved.
  * See COPYING.txt for license details.
  */
+
 declare(strict_types=1);

 namespace Magento\ConfigurableProduct\Model\Inventory;
@@ -83,27 +85,38 @@

         $criteria->setProductsFilter($productId);
         $stockItemCollection = $this->stockItemRepository->getList($criteria);
+
+        /** @var \Magento\CatalogInventory\Model\Stock\Item[] */
         $allItems = $stockItemCollection->getItems();
         if (empty($allItems)) {
+
             return;
         }
+
         $parentStockItem = array_shift($allItems);

         $childrenIds = $this->configurableType->getChildrenIds($productId);
+        $childrenIds = (is_array($childrenIds) && !empty($childrenIds) && is_array($childrenIds[0]))
+            ? $childrenIds[0]
+            : $childrenIds;
+
         $criteria->setProductsFilter($childrenIds);
         $stockItemCollection = $this->stockItemRepository->getList($criteria);
-        $allItems = $stockItemCollection->getItems();

+        /** @var \Magento\CatalogInventory\Model\Stock\Item[] */
+        $allItems = $stockItemCollection->getItems();
         $childrenIsInStock = false;
-
         foreach ($allItems as $childItem) {
+
             if ($childItem->getIsInStock() === true) {
+
                 $childrenIsInStock = true;
                 break;
             }
         }

         if ($this->isNeedToUpdateParent($parentStockItem, $childrenIsInStock)) {
+
             $parentStockItem->setIsInStock($childrenIsInStock);
             $parentStockItem->setStockStatusChangedAuto(1);
             $parentStockItem->setStockStatusChangedAutomaticallyFlag(true);
@@ -122,7 +135,7 @@
         StockItemInterface $parentStockItem,
         bool $childrenIsInStock
     ): bool {
-        return $parentStockItem->getIsInStock() !== $childrenIsInStock &&
-            ($childrenIsInStock === false || $parentStockItem->getStockStatusChangedAuto());
+
+        return $parentStockItem->getIsInStock() !== $childrenIsInStock;
     }
 }
```

**Comment by serzhik** [comment]
Patch [ACSD-48910](https://github.com/magento/quality-patches/blob/master/patches/os/ACSD-48910_1.2.5-p1.patch) fixed this issue for me. It works for Magento 2.4.5-x. (https://experienceleague.adobe.com/en/docs/commerce-knowledge-base/kb/support-tools/patches/v1-1-42/acsd-48910-bundle-product-assigned-to-multiple-sources-out-of-stock)

**Comment by nordcomputer** [comment]
> For those still experiencing issues where configurable products stock status fails to update when child products come back in-stock. I've created a patch which works for my Magento 2.4.6-p1 instance suffering from this virus...
> 
> --- a/vendor/magento/module-configurable-product/Model/Inventory/ChangeParentStockStatus.php	2024-06-27 11:54:34.515474442 +0100
> +++ b/vendor/magento/module-configurable-product/Model/Inventory/ChangeParentStockStatus.php	2024-06-27 11:56:33.263253341 +0100
> @@ -1,8 +1,10 @@
>  <?php
> +
>  /**
>   * Copyright © Magento, Inc. All rights reserved.
>   * See COPYING.txt for license details.
>   */
> +
>  declare(strict_types=1);
> 
>  namespace Magento\ConfigurableProduct\Model\Inventory;
> @@ -83,27 +85,38 @@
> 
>          $criteria->setProductsFilter($productId);
>          $stockItemCollection = $this->stockItemRepository->getList($criteria);
> +
> +        /** @var \Magento\CatalogInventory\Model\Stock\Item[] */
>          $allItems = $stockItemCollection->getItems();
>          if (empty($allItems)) {
> +
>              return;
>          }
> +
>          $parentStockItem = array_shift($allItems);
> 
>          $childrenIds = $this->configurableType->getChildrenIds($productId);
> +        $childrenIds = (is_array($childrenIds) && !empty($childrenIds) && is_array($childrenIds[0]))
> +            ? $childrenIds[0]
> +            : $childrenIds;
> +
>          $criteria->setProductsFilter($childrenIds);
>          $stockItemCollection = $this->stockItemRepository->getList($criteria);
> -        $allItems = $stockItemCollection->getItems();
> 
> +        /** @var \Magento\CatalogInventory\Model\Stock\Item[] */
> +        $allItems = $stockItemCollection->getItems();
>          $childrenIsInStock = false;
> -
>          foreach ($allItems as $childItem) {
> +
>              if ($childItem->getIsInStock() === true) {
> +
>                  $childrenIsInStock = true;
>                  break;
>              }
>          }
> 
>          if ($this->isNeedToUpdateParent($parentStockItem, $childrenIsInStock)) {
> +
>              $parentStockItem->setIsInStock($childrenIsInStock);
>              $parentStockItem->setStockStatusChangedAuto(1);
>              $parentStockItem->setStockStatusChangedAutomaticallyFlag(true);
> @@ -122,7 +135,7 @@
>          StockItemInterface $parentStockItem,
>          bool $childrenIsInStock
>      ): bool {
> -        return $parentStockItem->getIsInStock() !== $childrenIsInStock &&
> -            ($childrenIsInStock === false || $parentStockItem->getStockStatusChangedAuto());
> +
> +        return $parentStockItem->getIsInStock() !== $childrenIsInStock;
>      }
>  }

This also seems to work on 2.4.7-p3

**Comment by novikor** [comment]
> For those still experiencing issues where configurable products stock status fails to update when child products come back in-stock. I've created a patch which works for my Magento 2.4.6-p1 instance suffering from this virus...
> 
> --- a/vendor/magento/module-configurable-product/Model/Inventory/ChangeParentStockStatus.php	2024-06-27 11:54:34.515474442 +0100
> +++ b/vendor/magento/module-configurable-product/Model/Inventory/ChangeParentStockStatus.php	2024-06-27 11:56:33.263253341 +0100
> @@ -1,8 +1,10 @@
>  <?php
> +
>  /**
>   * Copyright © Magento, Inc. All rights reserved.
>   * See COPYING.txt for license details.
>   */
> +
>  declare(strict_types=1);
> 
>  namespace Magento\ConfigurableProduct\Model\Inventory;
> @@ -83,27 +85,38 @@
> 
>          $criteria->setProductsFilter($productId);
>          $stockItemCollection = $this->stockItemRepository->getList($criteria);
> +
> +        /** @var \Magento\CatalogInventory\Model\Stock\Item[] */
>          $allItems = $stockItemCollection->getItems();
>          if (empty($allItems)) {
> +
>              return;
>          }
> +
>          $parentStockItem = array_shift($allItems);
> 
>          $childrenIds = $this->configurableType->getChildrenIds($productId);
> +        $childrenIds = (is_array($childrenIds) && !empty($childrenIds) && is_array($childrenIds[0]))
> +            ? $childrenIds[0]
> +            : $childrenIds;
> +
>          $criteria->setProductsFilter($childrenIds);
>          $stockItemCollection = $this->stockItemRepository->getList($criteria);
> -        $allItems = $stockItemCollection->getItems();
> 
> +        /** @var \Magento\CatalogInventory\Model\Stock\Item[] */
> +        $allItems = $stockItemCollection->getItems();
>          $childrenIsInStock = false;
> -
>          foreach ($allItems as $childItem) {
> +
>              if ($childItem->getIsInStock() === true) {
> +
>                  $childrenIsInStock = true;
>                  break;
>              }
>          }
> 
>          if ($this->isNeedToUpdateParent($parentStockItem, $childrenIsInStock)) {
> +
>              $parentStockItem->setIsInStock($childrenIsInStock);
>              $parentStockItem->setStockStatusChangedAuto(1);
>              $parentStockItem->setStockStatusChangedAutomaticallyFlag(true);
> @@ -122,7 +135,7 @@
>          StockItemInterface $parentStockItem,
>          bool $childrenIsInStock
>      ): bool {
> -        return $parentStockItem->getIsInStock() !== $childrenIsInStock &&
> -            ($childrenIsInStock === false || $parentStockItem->getStockStatusChangedAuto());
> +
> +        return $parentStockItem->getIsInStock() !== $childrenIsInStock;
>      }
>  }

It seems the `cataloginventory_stock_item.stock_status_changed_auto` is the root cause of all the problems.

If you create a configurable product from admin and set it to Out of Stock initially, it will be never in stock then again by puting its children to In Stock.

Wonderful.

Checked on `2.4.7-p3` with Default Source used: the patch is still helpful.

That is more likely a dirty fix and might cause issues when you want to put the Configurable Out of Stock manually on purpose - but anyway it's a rare case, and moreover, it's less an issue that being unable to transfer it back to stock.

The case I have mentioned is **not related to the MSI** and not directly related to the problem initially reported there

**Comment by engcom-November** [comment]
Hello,

Based on the [comment](https://github.com/magento/inventory/pull/3393#issuecomment-3401777322) provided, we will now proceed to close this issue. 

If the issue persists, please feel free to reopen this ticket or submit a new one.

Thank You!

**Comment by novikor** [comment]
> Hello,
> 
> Based on the [comment](https://github.com/magento/inventory/pull/3393#issuecomment-3401777322) provided, we will now proceed to close this issue.
> 
> If the issue persists, please feel free to reopen this ticket or submit a new one.
> 
> Thank You!

Do I understand correctly that, as a solution for incorrect stock status calculation, you suggest disabling the "Manage Stock" config? We might disable the stocks globally and close the MSI (Inventory) project altogether.
